package com.paolomanlunas.countriesapp.model;

import java.util.List;

import io.reactivex.Single;
import retrofit2.http.GET;

public interface CountriesApi {

   // 'Single' is a type of Observable generated by RxJava, that only emits ONE value - then finishes
   // SINGLE is an RxJava Component that is an OBSERVABLE.
   @GET("/DevTides/countries/master/countriesV2.json")
   Single<List<CountryModel>> getCountries();
}
